function [fitresult, gof] = myGausFit(x, sumX, wx)
%CREATEFIT(X,SUMX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: sumX
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Nov-2020 16:06:56


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, sumX );

% Set up fittype and options.
ft = fittype( 'a0 + a*exp(-((x-b)/c)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Trust-Region';
opts.Weights = wx;
opts.Display = 'Off';
opts.Lower = [0 0 -100 0];
opts.Robust = 'LAR';
opts.StartPoint = [0.3619 0 0 0.7449];
opts.Upper = [Inf 0 100 100];

% Fit model to data after fixing baseline
[fitresult, gof] = fit( xData, yData, ft, opts );

% opts.StartPoint = coeffvalues(fitresult);
% opts.Lower(2) = opts.StartPoint(2);
% opts.Upper(2) = opts.StartPoint(2);
% 
% [fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'sumX vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'sumX', 'Interpreter', 'none' );
% grid on


