function [D, errD] = getChannelDoseT1_wErrors(CoefX, PVX, dCoefX, dPVX)
    D = CoefX(3) + CoefX(2) ./ (PVX - CoefX(1));
    errD = sqrt( dCoefX(3).^2 + ...
                (dCoefX(2)./(PVX-CoefX(1))).^2 + ...
                (CoefX(2).*dPVX./(PVX-CoefX(1).^2)).^2 + ...
                (CoefX(2).*dCoefX(1)./(PVX-CoefX(1).^2)).^2);
end

