function [fitresult, gof] = fitTypeII(dosesGy, aa, aa_errors)
%CREATEFIT(DOSESGY,AA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : dosesGy
%      Y Output: aa
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Aug-2020 12:22:06

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( dosesGy, aa );

% Set up fittype and options.
ft = fittype( 'poly3');
opts = fitoptions( 'poly3' );
%opts.Display = 'Off';
%opts.Robust = 'LAR';
opts.Weights = aa_errors.^(-2);
%opts.StartPoint = [-0.80 0.24 0.04];
% Fit model to data.
%[fitresult] = fit( xData, yData, ft, opts);

[fitresult, gof] = fit( xData, yData, ft, opts);
% % Plot fit with data.

% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% hold on
% errorbar(xData, yData, aa_errors, 'b.');
% legend( h, 'aa vs. dosesGy', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'dosesGy', 'Interpreter', 'none' );
% ylabel( 'aa', 'Interpreter', 'none' );
% grid on


